services:
  db-postgres-graphql-app-technical-test:
    container_name: db-postgres-rick-morty-graphql-technical-test
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  node-rick-morty-graphql-technical-test:
    container_name: node-rick-morty-graphql-technical-test
    build: .
    restart: always
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db-postgres-graphql-app-technical-test
    volumes:
      - .:/app
    networks:
      - app-network
    command: ["npm", "run", "migrate-and-dev"]

volumes:
  postgres_db_data:

networks:
  app-network:
    driver: bridge
